### ISSUE TITLE
Render problem in layout xml file

### ISSUE THREAD

**Issue by AlexSheva-mason** [quiph/RecyclerView-FastScroller#13]
Having this error in the layout file. FastScroller works alright though.
How can I fix this? My repo
https://github.com/AlexSheva-mason/Rickypedia

```
java.lang.NullPointerException
	at android.graphics.Canvas_Delegate.nGetClipBounds(Canvas_Delegate.java:418)
	at android.graphics.Canvas.nGetClipBounds(Canvas.java)
	at android.graphics.Canvas.getClipBounds(Canvas.java:1261)
	at android.text.Layout.getLineRangeForDraw(Layout.java:672)
	at android.text.Layout.draw(Layout.java:317)
	at android.text.BoringLayout.draw(BoringLayout.java:460)
	at android.widget.TextView.onDraw(TextView.java:7976)
	at android.view.View.draw_Original(View.java:21443)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:404)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:565)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:425)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:120)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:151)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:133)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$9(RenderTask.java:819)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by shahsurajk** [comment]
I don't think this issue concerns this library. 

Closing it. Re-open if you feel it's cause of this library.
