### ISSUE TITLE
Crash Fatal error  android.widget.ImageView cannot be cast to androidx.appcompat.widget.AppCompatImageView

### ISSUE THREAD

**Issue by omkar-tenkale** [quiph/RecyclerView-FastScroller#19]
App crash when fragment is shown

I'm using vector drawable support library
Maybe that's causing this issue   
```

defaultConfig {
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        **vectorDrawables.useSupportLibrary = true**


        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }
```

```
android.view.InflateException: Binary XML file line #9 in com.pkg:layout/fragment_gallery_album_picker: Binary XML file line #9 in com.pkg:layout/fragment_gallery_album_picker: Error inflating class com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller
    Caused by: android.view.InflateException: Binary XML file line #9 in com.pkg:layout/fragment_gallery_album_picker: Error inflating class com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.pkg.VideoPickerFragment.onCreateView(VideoPickerFragment.java:62)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassCastException: android.widget.ImageView cannot be cast to androidx.appcompat.widget.AppCompatImageView
        at com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller.addThumbAndTrack(Unknown Source:20)
2020-08-28 02:33:37.179 E:     at com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller.<init>(Unknown Source:58)
        at com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller.<init>(Unknown Source:10)
        at com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller.<init>(Unknown Source:6)
```

**Comment by shahsurajk** [comment]
closing due to inactivity.

**Comment by omkar-tenkale** [comment]
Wait.. what?

**Comment by omkar-tenkale** [comment]
This is a valid issue,you can't simply close this before it getting other people's attention!
