### ISSUE TITLE
Error inflating class com.qtalk.recyclerviewfastscroller.RecyclerViewFastScrolle

### ISSUE THREAD

**Issue by imayank91** [quiph/RecyclerView-FastScroller#4]
```
 android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller
    Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller
    Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
        at java.lang.Class.getConstructor0(Class.java:2327)
        at java.lang.Class.getConstructor(Class.java:1725)
        at android.view.LayoutInflater.createView(LayoutInflater.java:615)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
```

**Comment by shahsurajk** [comment]
Hi @imayank91 could you provide some details as to what is happening? Also are you using AndroidX? 

If not, try switching to an older version, maybe this could help: 
`implementation 'com.quiph.ui:recyclerviewfastscroller:0.1.1-alpha'`

**Comment by imayank91** [comment]
Yeah, I am using AndroidX.

**Comment by imayank91** [comment]
I have implemented the below version 

`implementation 'com.quiph.ui:recyclerviewfastscroller:0.1.2'`

and upon running I get the error I mentioned.

**Comment by shahsurajk** [comment]
Okay, and you don't have proguard/ minify set as true as well?

**Comment by imayank91** [comment]
This is my buildType

```
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
//            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            testCoverageEnabled true
//            debuggable true
            signingConfig signingConfigs.release
        }
    }
```

**Comment by shahsurajk** [comment]
Could you paste your layout XML file as well, only the root and the recyclerview-fastscroller tag would be enough.

**Comment by imayank91** [comment]
This is my XML file

```
<com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller xmlns:app="http://schemas.android.com/apk/res-auto"
                                                             xmlns:android="http://schemas.android.com/apk/res/android"
                                                             android:layout_width="match_parent"
                                                             android:layout_height="match_parent"
                                                             android:id="@+id/fast_scroller_contacts"
                                                             app:handleWidth="@dimen/default_handle_size"
                                                             app:handleHeight="32dp"
                                                             app:popupTextStyle="@style/ContactsPopupTextViewStyle"
                                                             app:popupDrawable="@drawable/contacts_fastscroller_drawable">
    <androidx.recyclerview.widget.RecyclerView
            android:layout_height="match_parent"
            android:layout_width="match_parent"
            android:layout_marginStart="@dimen/_4sdp"
            android:layout_marginEnd="@dimen/_4sdp"
            android:id="@+id/contacts_recycler_view">
    </androidx.recyclerview.widget.RecyclerView>
</com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller>
```

**Comment by shahsurajk** [comment]
What is the OS of the device it is crashing on? Before some version of Android, constructors had only 2 parameters. And the crash clearly points to the constructor.

**Comment by imayank91** [comment]
Android 9 , API 28

**Comment by shahsurajk** [comment]
Then it should not be a problem. Let me re-compile and check it.

**Comment by imayank91** [comment]
Sure, let me know

**Comment by shahsurajk** [comment]
Hi @imayank91, so we confirmed the problem, it's an internal error made by us during the packaging of the library. We've added rules so this doesn't occur again. Thanks a lot for pointing this out to us. 

Meanwhile, here's a list of things you could do: 
1. Wait for 0.1.3 to get released. This is already in progress and will go live in a day or so. This issue will automatically get closed when it will released.
2. If you can't wait, you can clone the project and use it as a module dependency, Check [this](https://stackoverflow.com/questions/25610727/adding-external-library-in-android-studio) SO post.

**Comment by imayank91** [comment]
Ok, It'll be helpful you can patch it tomorrow.

**Comment by shahsurajk** [comment]
@imayank91 v0.1.3 is already released. It can take a few hours for the dependencies to become available. This release should solve this issue
