### ISSUE TITLE
Crash - lateinit property recyclerView has not been initialized

### ISSUE THREAD

**Issue by omkar-tenkale** [quiph/RecyclerView-FastScroller#51]
kotlin.UninitializedPropertyAccessException: lateinit property recyclerView has not been initialized
        at com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller.access$getRecyclerView$p(Unknown Source:6)
        at com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller$alignTrackAndHandle$5.run(Unknown Source:111)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by omkar-tenkale** [comment]
Happens after recycler is initialized with adapter and then the fastscroll.attach is called
